
	import dataList from '../../components/trades/datalist.vue'
	import historylog from '../../components/trades/historylog.vue'
	import tradelist from '../../components/tradeitem/index.vue'
    import pageFooter from '@/components/common/footer.vue'
	export default {
	  components: {dataList,historylog,tradelist,pageFooter},
	  methods:{
	  		  judgedata(){
	  		  			  if(this.showdata){
	  		  				  this.showdata=true,
	  		  				  this.shownodata=false
	  		  			  }
	  		  },
			  gohistorylog(){
			  		this.$jumpPage.jump({
					type:'navigateTo',
			  		url:'historylist/index'
			  	})
			  }
	  },
	  created(){
	  		  this.judgedata();
	  },
	  data(){
	    return{
			green:{
				bgc:"#DEF4E7",
				fonts_color:"#5BC788"
			},
			red:{
				bgc:"#FEEBEE",
				fonts_color:"#FC3C5A"
			},
			tradesOptions_list:[
				{
					money:"0.0653",
					num:"500"
				},
				{
					money:"0.0653",
					num:"500"
				},
				{
					money:"0.0653",
					num:"500"
				},
				{
					money:"0.0653",
					num:"500"
				},
			],
			historylogdata_list:[
				{
					charge:10,
					num:0.98
				},
				{
					charge:20,
					num:1.98
				},
				{
					charge:30,
					num:2.98
				},
			],
			tradelistOptions:[
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+3.0%",
					status:0
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+4.0%",
					status:1
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+3.0%",
					status:0
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+4.0%",
					status:1
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+3.0%",
					status:0
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+4.0%",
					status:1
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+3.0%",
					status:0
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+4.0%",
					status:1
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+3.0%",
					status:0
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+4.0%",
					status:1
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+3.0%",
					status:0
				},
				{
					type:"USDT/BRT",
					number:"14.5689",
					per:"+4.0%",
					status:1
				},
			],
			showmask:false,
			shownodata:true,
			showdata:true
		}
	  }
	};
